### `Building Baseline Statistical Model Benchmark`

`Importing Libraries`

In [5]:
import pandas as pd
import numpy as np

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score, root_mean_squared_error

from statsmodels.tsa.statespace.sarimax import SARIMAX
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf

import warnings
warnings.filterwarnings('ignore')

`Loading Dataset`

In [6]:
consumption_hourly = pd.read_csv('../dataset/consumption_hourly.csv', na_values='?', index_col='Datetime', parse_dates=True)
consumption_daily = pd.read_csv('../dataset/consumption_daily.csv', na_values='?', index_col='Datetime', parse_dates=True)

In [7]:
consumption_hourly.head()

,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3,hour,day_of_week,month,year,is_weekend,season,lag_1h,lag_24h,rolling_mean_6h,rolling_mean_24h
Datetime,,,,,,,,,,,,,,,,,
2006-12-17 17:00:00,3.406767,0.166633,234.229833,14.510000,0.0,0.466667,16.816667,17,6,12,2006,1,Winter,3.326033,4.222889,2.564578,2.465140
2006-12-17 18:00:00,3.697100,0.135067,234.372333,15.750000,0.0,0.000000,16.833333,18,6,12,2006,1,Winter,3.406767,3.632200,2.861450,2.467844
2006-12-17 19:00:00,2.908400,0.265167,233.195667,12.516667,0.0,0.516667,16.683333,19,6,12,2006,1,Winter,3.697100,3.400233,3.069389,2.447351
2006-12-17 20:00:00,3.361500,0.271500,236.426500,14.276667,0.0,1.116667,17.116667,20,6,12,2006,1,Winter,2.908400,3.268567,3.280867,2.451224
2006-12-17 21:00:00,3.040767,0.267967,239.104167,12.716667,0.0,1.200000,17.500000,21,6,12,2006,1,Winter,3.361500,3.056467,3.290094,2.450569

In [8]:
consumption_daily.head()

,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
Datetime,,,,,,,
2006-12-16,3.053475,0.088187,236.243763,13.082828,0.000000,1.378788,12.439394
2006-12-17,2.354486,0.156949,240.087028,9.999028,1.411806,2.907639,9.264583
2006-12-18,1.530435,0.112356,241.231694,6.421667,0.738194,1.820139,9.734722
2006-12-19,1.157079,0.104821,241.999313,4.926389,0.582639,5.279167,4.303472
2006-12-20,1.545658,0.111804,242.308063,6.467361,0.000000,1.838889,9.765972

In [ ]:
# Target: hourly Global Active Power (GAP)
target = consumption_hourly['Global_active_power']